# Generated by Django 2.1.1 on 2018-09-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_framework_tracking', '0007_merge_20180419_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apirequestlog',
            name='view_method',
            field=models.CharField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
